apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend5-tcp
  name: frontend5-tcp
spec:
  ports:
    - name: "8005"
      port: 8005
      targetPort: 8080
  selector:
    io.kompose.service: frontend5
  type: LoadBalancer
status:
  loadBalancer: {}
