apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend2
  name: frontend2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend2
    spec:
      containers:
        - env:
            - name: SWAGGER_JSON
              value: /AOSgestionvehiculos/vehiculos.yaml
          image: swaggerapi/swagger-ui
          name: vehiculosgestion-ui
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /AOSgestionvehiculos
              name: frontend2-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: frontend2-claim0
          persistentVolumeClaim:
            claimName: frontend2-claim0
            readOnly: true
status: {}
