apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend7
  name: frontend7
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend7
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend7
    spec:
      containers:
        - env:
            - name: SWAGGER_JSON
              value: /openapi/logs.yaml
          image: swaggerapi/swagger-ui:latest
          name: logs-ui
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /openapi
              name: frontend7-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: frontend7-claim0
          persistentVolumeClaim:
            claimName: frontend7-claim0
            readOnly: true
status: {}
