apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: subsistema3
  name: subsistema3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: subsistema3
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: subsistema3
    spec:
      containers:
        - image: subsistema3
          name: subsistema3
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
