version: "3"

services:
    frontend1:
        image: swaggerapi/swagger-ui
        container_name: clientes_ui
        ports:
            - 8001:8080
        environment:
            SWAGGER_JSON: /AOS/clientes.yaml
        volumes:
            - ./OpenApi:/AOS:ro
        labels:
            kompose.service.type: LoadBalancer

    backend1:
        image: stoplight/prism:4
        container_name: clientes_mock
        command: mock --cors -h 0.0.0.0 "/AOS/clientes.yaml"
        ports:
          - 4011:4010
        volumes:
            - ./OpenApi:/AOS:ro
        labels:
            kompose.service.type: LoadBalancer

    frontend2:
        image: swaggerapi/swagger-ui
        container_name: vehiculosGestion_ui
        ports:
            - 8002:8080
        environment:
            SWAGGER_JSON: /AOSgestionvehiculos/vehiculos.yaml
        volumes:
            - ./OpenApi:/AOSgestionvehiculos:ro
        labels:
            kompose.service.type: LoadBalancer

    backend2:
        image: stoplight/prism:4
        container_name: vehiculosGestion_mock
        command: mock --cors -h 0.0.0.0 "/AOSgestionvehiculos/vehiculos.yaml"
        ports:
          - 4012:4010
        volumes:
            - ./openapi:/AOSgestionvehiculos:ro
        labels:
            kompose.service.type: LoadBalancer

    subsistema3:
        build: /subs3/.
        ports:
            - 8003:3000
        labels:
            kompose.service.type: LoadBalancer

    frontend4:
        image: swaggerapi/swagger-ui
        container_name: notificaciones_ui
        ports:
            - 8004:8080
        environment:
            SWAGGER_JSON: /aos/notificaciones.yaml
        volumes:
            - ./openapi:/aos:ro

    backend4:
        image: stoplight/prism:4
        container_name: notificaciones_mock
        command: mock --cors -h 0.0.0.0 "/aos/notificaciones.yaml"
        ports:
          - 4014:4010
        volumes:
            - ./openapi:/aos:ro

    frontend5:
        image: swaggerapi/swagger-ui
        container_name: facturas_ui
        ports:
            - 8005:8080
        environment:
            SWAGGER_JSON: /aos/facturas.yaml
        volumes:
            - ./openapi:/aos:ro

    backend5:
        image: stoplight/prism:4
        container_name: facturas_mock
        command: mock --cors -h 0.0.0.0 "/aos/facturas.yaml"
        ports:
            - 4015:4010
        volumes:
            - ./openapi:/aos:ro

    frontend6:
        image: swaggerapi/swagger-ui:latest
        container_name: recambios_ui
        ports:
            - "8006:8080"
        environment:
            SWAGGER_JSON: /recambios/openapi.yaml
        volumes:
            - ./openapi-recambios:/recambios:ro

    backend6:
        image: stoplight/prism:4
        container_name: recambios_mock
        command: mock --cors -h 0.0.0.0 "/recambios/openapi.yaml"
        ports:
            - "4016:4010"
        volumes:
            - ./openapi-recambios:/recambios:ro

    frontend7:
        image: swaggerapi/swagger-ui:latest
        container_name: logs_ui
        ports:
            - "8007:8080"
        environment:
            SWAGGER_JSON: /openapi/logs.yaml
        volumes:
            - ./openapi:/openapi:ro
            
    backend7:
        image: stoplight/prism:4
        container_name: log_mocks
        command: mock --cors -h 0.0.0.0 "/openapi/logs.yaml"
        ports:
          - "4017:4010"
        volumes:
            - ./openapi:/openapi:ro
            
    proxy:
        image: caddy:latest
        container_name: logs_proxy
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfiledocker 
            - ./caddy_data:/data
        ports:
            - "80:80"
        depends_on:
            - backend1
            - backend7